const LoginRegActionTypes={
SET_CURRENT_USER: 'SET_CURRENT_USER',
SET_ISLOG : 'SET_ISLOG',
CHECK_USER_SESSION:'CHECK_USER_SESSION',
SIGN_IN_START : 'SIGN_IN_START',
SIGN_IN_SUCCESS : 'SIGN_IN_SUCCESS',
SIGN_IN_FAILURE : 'SIGN_IN_FAILURE',
SIGN_UP_START : 'SIGN_UP_START',
SIGN_UP_SUCCESS : 'SIGN_UP_SUCCESS',
SIGN_UP_FAILURE : 'SIGN_UP_FAILURE',
GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
FACEBOOK_SIGN_IN_START: 'FACEBOOK_SIGN_IN_START',
SIGN_OUT_START: 'SIGN_OUT_START',
SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
RESET_ERROR_MESSAGE : 'RESET_ERROR_MESSAGE'
}

export default LoginRegActionTypes;