export const FETCH_LOGIN_SUCCESS = 'FETCH_SIGNIN_SUCCESS'
export const FETCH_LOGIN_FAILS = 'FETCH_SIGNIN_FAILS'
export const FETCH_LOGIN_BEGIN = 'FETCH_SIGNIN_BEGIN'

export const FETCH_SIGNUP_SUCCESS = 'FETCH_SIGNUP_SUCCESS'
export const FETCH_SIGNUP_FAILS = 'FETCH_SIGNUP_FAILS'
export const FETCH_SIGNUP_BEGIN = 'FETCH_SIGNUP_BEGIN'

export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE'
export const SET_ISLOG = 'SET_ISLOG'
